.TH MOSERIAL "1" "February 2010"
.SH NAME
moserial \- moserial serial terminal
.SH DESCRIPTION
.SS "Usage:"
.IP
moserial [OPTION...]
.SS "Help Options:"
.TP
\fB\-?\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-p\fR, \fB\-\-profile\fR=\fIfoo\fR.conf
Profile file to load
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.PP
Run 'moserial \fB\-\-help\fR' to see a full list of available command line options.
